| 节点                    | 建议              |
| --------------------- | --------------- |
| CameraFeature         | 画icon           |
| LidarFeature          | 画icon           |
| StatusFeature         | 画icon           |
| BEVBackbone           | 画BEV图           |
| FlattenBevFeature     | 方块              |
| Diffv2PlannerSampling | 画icon           |
| TrajectorySamples     | 画trajectory     |
| EgoTrajEncoder        | 小icon或方块        |
| EgoFeatToken          | 方块              |
| OffsetHead            | 方块              |
| TrajectoryOffset      | 方块              |
| LatentWorldModel      | 画icon           |
| FutEgoFeat            | 方块              |
| MemoryWrite           | 方块              |
| MemoryPool            | 画memory         |
| RagRetriever          | 画icon           |
| RetrievedMemory       | 画icon           |
| RewardHead            | 画icon           |
| FinalRewards          | 方块              |
| AddAnchorOffset       | 方块              |
| RefinedTraj           | 画trajectory     |
| SelectBestTraj        | 画icon           |
| BestTraj              | 画trajectory（突出） |
